name: Maven Release

on:
    workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Cache
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Run tests
        run: mvn test

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jar-file
          path: target/*.jar

  docker:
    needs: build
    uses: ./.github/workflows/Docker.yml
    secrets: inherit
